DOUBAN_COOKIES:
  bid: "your_bid"
  dbcl2: "your_dbcl2"
  ck: "your_ck"

user_id: "your_douban_user_id"
start_page: 0
START_DATE: "20240101"
MOVIE_CSV_FILE: "movie.csv"
MISSING_IMDB_CSV_FILE: "missing_imdb.csv"
CHROMEDRIVER_PATH: "C:/path/to/chromedriver.exe"
